"""Added DateTime

Revision ID: 4b0e25ceea35
Revises: 
Create Date: 2021-04-03 04:36:29.019736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0e25ceea35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('waec_registration', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waec_registration', 'date_created')
    op.drop_column('registration', 'date_created')
    # ### end Alembic commands ###
