"""empty message

Revision ID: 8f3f6af8c46c
Revises: 4b0e25ceea35
Create Date: 2021-04-06 00:06:52.148529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3f6af8c46c'
down_revision = '4b0e25ceea35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nursing_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('othernames', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dateOfBirth', sa.String(), nullable=True),
    sa.Column('placeOfBirth', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('medicalCondition', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('regionDistrict', sa.String(), nullable=True),
    sa.Column('digitalAddress', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('guardianName', sa.String(), nullable=True),
    sa.Column('indexNo', sa.String(), nullable=True),
    sa.Column('examsYear', sa.String(), nullable=True),
    sa.Column('waecCourse', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nursing_registration')
    # ### end Alembic commands ###
